version: "3.8"

services:
  app:
    build: .
    container_name: bharatfd_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcloud-credentials.json
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - ./gcloud-credentials/nodetalk-24565-e37341a09bca.json:/app/gcloud-credentials.json:ro
    restart: always

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
